version: 2.1

jobs:
  build:
    working_directory: ~/SimpleApplication
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@5
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "<your_ssh_key_fingerprint_here>" # optional if SSH keys set in CircleCI
      - run: 
          name: deploy-application
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_DevOpsLab@$EC2_PUBLIC_DNS "
              rm -rf SimpleApplication;
              git clone https://github.com/JakubSieron/SimpleApplication.git;
              source SimpleApplication/deploy.sh
            "

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main


